changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - "feature"
        - "feat"
    - title: "🐛 Fixes"
      labels:
        - "fix"
        - "bug"
    - title: "🧪 Tests"
      labels:
        - "test"
        - "tests"
    - title: "🧰 Maintenance"
      labels:
        - "chore"
        - "ci"
        - "build"
  exclude:
    labels:
      - "ignore"
