sonar.projectKey=MoviesXMovies-Frontend

sonar.sources=src
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.d.ts, src/assets/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts, **/*.test.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8